"""empty message

Revision ID: 13bf53f06815
Revises: cb5464c8da5a
Create Date: 2025-11-26 10:49:47.866887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bf53f06815'
down_revision = 'cb5464c8da5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workStatus', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('agency', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('agency')
        batch_op.drop_column('workStatus')

    # ### end Alembic commands ###
