"""empty message

Revision ID: 189040114145
Revises: e3c20802cd2d
Create Date: 2026-01-23 16:14:59.206756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189040114145'
down_revision = 'e3c20802cd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('methodology2', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.drop_column('methodology2')

    # ### end Alembic commands ###
