"""empty message

Revision ID: 1e32e62a614f
Revises: fa20c973d1a8
Create Date: 2026-01-22 17:02:18.054308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e32e62a614f'
down_revision = 'fa20c973d1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agencies', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.drop_column('agencies')

    # ### end Alembic commands ###
