"""empty message

Revision ID: 31fa0e7c1629
Revises: a1ec00819c9d
Create Date: 2025-10-31 14:54:52.586773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fa0e7c1629'
down_revision = 'a1ec00819c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('students_email_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['filename'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('students_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
