"""empty message

Revision ID: 3a79eaa0e315
Revises: e317e7f9ec2f
Create Date: 2026-02-04 12:41:11.471539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a79eaa0e315'
down_revision = 'e317e7f9ec2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefitStatus', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.drop_column('benefitStatus')

    # ### end Alembic commands ###
