"""empty message

Revision ID: 4116a7926e10
Revises: 46128667bf27
Create Date: 2025-10-31 17:27:17.134581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4116a7926e10'
down_revision = '46128667bf27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduationDate', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('certiDate', sa.String(length=20), nullable=True))
        batch_op.drop_column('certidate')
        batch_op.drop_column('graduationdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduationdate', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certidate', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('certiDate')
        batch_op.drop_column('graduationDate')

    # ### end Alembic commands ###
