"""empty message

Revision ID: 46128667bf27
Revises: 31fa0e7c1629
Create Date: 2025-10-31 16:40:53.068920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46128667bf27'
down_revision = '31fa0e7c1629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduationDate', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('certiDate', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('certiDate')
        batch_op.drop_column('graduationDate')

    # ### end Alembic commands ###
