"""empty message

Revision ID: 767675a42915
Revises: 4116a7926e10
Create Date: 2025-11-03 12:58:46.795369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767675a42915'
down_revision = '4116a7926e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
