"""empty message

Revision ID: 80c3330b183f
Revises: de362f2e3724
Create Date: 2025-11-26 13:19:33.990419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c3330b183f'
down_revision = 'de362f2e3724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('campaign', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('campaign')
        batch_op.drop_column('lot')

    # ### end Alembic commands ###
