"""empty message

Revision ID: 8138d7a30320
Revises: 767675a42915
Create Date: 2025-11-03 15:25:40.236630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8138d7a30320'
down_revision = '767675a42915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sessionType', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('sessionType')
        batch_op.drop_column('days')

    # ### end Alembic commands ###
