"""empty message

Revision ID: 8deded6b06da
Revises: f09d0fe8a80b
Create Date: 2025-10-30 13:22:41.235087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8deded6b06da'
down_revision = 'f09d0fe8a80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('modules', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('receiptDates', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('receiptDates')
        batch_op.drop_column('modules')
        batch_op.drop_column('units')

    # ### end Alembic commands ###
