"""empty message

Revision ID: a1ec00819c9d
Revises: fe042b6eb723
Create Date: 2025-10-31 14:48:14.888958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ec00819c9d'
down_revision = 'fe042b6eb723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('students_filename_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('students_filename_key'), ['filename'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
