"""Initial

Revision ID: cb5464c8da5a
Revises: 
Create Date: 2025-11-21 12:15:25.103350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb5464c8da5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('startDate', sa.String(), nullable=False),
    sa.Column('endDate', sa.String(), nullable=False),
    sa.Column('graduationDate', sa.String(), nullable=False),
    sa.Column('certiDate', sa.String(), nullable=False),
    sa.Column('teacher', sa.String(), nullable=False),
    sa.Column('hours', sa.String(), nullable=False),
    sa.Column('days', sa.String(), nullable=True),
    sa.Column('sessionType', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=False),
    sa.Column('registration', sa.String(), nullable=False),
    sa.Column('tuition', sa.String(), nullable=False),
    sa.Column('dateUnits', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dateModules', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('classType', sa.Integer(), nullable=False),
    sa.Column('midpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('middleName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=False),
    sa.Column('ssn', sa.String(length=20), nullable=False),
    sa.Column('studentId', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('units', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('modules', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('receiptDates', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('classId', sa.Integer(), nullable=False),
    sa.Column('graduationDate', sa.String(length=20), nullable=True),
    sa.Column('certiDate', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('classes')
    # ### end Alembic commands ###
