"""empty message

Revision ID: d08351c23d8d
Revises: 5bc6dce10f52
Create Date: 2025-10-30 15:30:53.977729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd08351c23d8d'
down_revision = '5bc6dce10f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('startDate', sa.String(), nullable=False),
    sa.Column('endDate', sa.String(), nullable=False),
    sa.Column('graduationDate', sa.String(), nullable=False),
    sa.Column('certiDate', sa.String(), nullable=False),
    sa.Column('teacher', sa.String(), nullable=False),
    sa.Column('hours', sa.String(), nullable=False),
    sa.Column('total', sa.String(), nullable=False),
    sa.Column('registration', sa.String(), nullable=False),
    sa.Column('tuition', sa.String(), nullable=False),
    sa.Column('dataUnits', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dataModules', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('classType', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    # ### end Alembic commands ###
