"""empty message

Revision ID: e317e7f9ec2f
Revises: e8ee272a4808
Create Date: 2026-01-24 10:22:47.944635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e317e7f9ec2f'
down_revision = 'e8ee272a4808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workStartDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.drop_column('workStartDate')

    # ### end Alembic commands ###
