"""empty message

Revision ID: e3c20802cd2d
Revises: 1e32e62a614f
Create Date: 2026-01-22 18:27:36.231153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c20802cd2d'
down_revision = '1e32e62a614f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workStatus', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('queryStatus', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.drop_column('queryStatus')
        batch_op.drop_column('workStatus')

    # ### end Alembic commands ###
