"""empty message

Revision ID: e8ee272a4808
Revises: 189040114145
Create Date: 2026-01-23 16:33:03.006683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ee272a4808'
down_revision = '189040114145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certifiedDate2', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrap', schema=None) as batch_op:
        batch_op.drop_column('certifiedDate2')

    # ### end Alembic commands ###
