"""empty message

Revision ID: ed18b6d28a40
Revises: d08351c23d8d
Create Date: 2025-10-30 18:03:14.160279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed18b6d28a40'
down_revision = 'd08351c23d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateUnits', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('dateModules', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('dataModules')
        batch_op.drop_column('dataUnits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataUnits', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dataModules', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.drop_column('dateModules')
        batch_op.drop_column('dateUnits')

    # ### end Alembic commands ###
