"""empty message

Revision ID: f09d0fe8a80b
Revises: fb39a6717378
Create Date: 2025-10-30 11:32:15.421895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09d0fe8a80b'
down_revision = 'fb39a6717378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('middleName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=False),
    sa.Column('ssn', sa.String(length=10), nullable=False),
    sa.Column('studentId', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('filename')
    )
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('middleName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dob', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ssn', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('studentId', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('payload', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('student_pkey')),
    sa.UniqueConstraint('email', name=op.f('student_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('filename', name=op.f('student_filename_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('students')
    # ### end Alembic commands ###
