"""empty message

Revision ID: fa20c973d1a8
Revises: 80c3330b183f
Create Date: 2026-01-22 12:46:59.042136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa20c973d1a8'
down_revision = '80c3330b183f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.String(length=100), nullable=False),
    sa.Column('startDate', sa.String(length=100), nullable=False),
    sa.Column('certifiedDate', sa.String(length=100), nullable=False),
    sa.Column('registryNumber', sa.String(length=100), nullable=True),
    sa.Column('methodology', sa.String(length=200), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrap')
    # ### end Alembic commands ###
